version: '3.4'

services:
  triplederby.api:
    image: ${DOCKER_REGISTRY-}triplederbyapi
    build:
      context: .
      dockerfile: src/TripleDerby.Api/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        MSSQL_SA_PASSWORD: "Pa55w0rd2019"
        ACCEPT_EULA: "Y"
    ports: 
      - "1445:1433" 